server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://oh-marking.com:8761/eureka

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user
          uri: http://oh-marking.com:8082/
#          uri: lb://??? ??? ??
          predicates:
            - Path=/user/**
#          filters:
#            - RewritePath=/user/(?<segment>.*), /$\{segment}
        - id: logic
          uri: http://oh-marking.com:8083/
#          uri: lb://??? ??? ??
          predicates:
            - Path=/logic/**
#          filters:
#            - RewritePath=/logic/(?<segment>.*), /$\{segment}
