server:
  port: 8081
  servlet:
    context-path: /api

spring:
  application:
    name: user-service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    url: jdbc:mysql://mysql_user:3306/ohmarking?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=UTF-8
    url: jdbc:mysql://localhost:3306/ohmarking?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=UTF-8
    username: root
    #    password: c102akdlsql
    password: 1234

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show-sql: true
        format_sql: true



logging:
  level:
    org:
      hibernate:
        SQL: debug
